var hierarchy =
[
    [ "PRISMS::Bin< T, Coordinate >", "class_p_r_i_s_m_s_1_1_bin.html", null ],
    [ "PRISMS::Body< Coordinate, DIM >", "class_p_r_i_s_m_s_1_1_body.html", null ],
    [ "PRISMS::Coordinate< DIM >", "class_p_r_i_s_m_s_1_1_coordinate.html", null ],
    [ "crystalOrientationsIO< dim >", "classcrystal_orientations_i_o.html", null ],
    [ "ellipticBVP", null, [
      [ "continuumPlasticity< dim >", "classcontinuum_plasticity.html", null ]
    ] ],
    [ "enhancedStrain< dim >", "classenhanced_strain.html", null ],
    [ "EquationDependencyParser", "class_equation_dependency_parser.html", null ],
    [ "Field< dim >", "class_field.html", null ],
    [ "FloodFiller< dim, degree >", "class_flood_filler.html", null ],
    [ "dealii::Function", null, [
      [ "InitialCondition< dim, degree >", "class_initial_condition.html", null ],
      [ "InitialConditionPField< dim >", "class_initial_condition_p_field.html", null ],
      [ "InitialConditionVector< dim, degree >", "class_initial_condition_vector.html", null ],
      [ "NonUniformDirichletBC< dim, degree >", "class_non_uniform_dirichlet_b_c.html", null ],
      [ "NonUniformDirichletBCVector< dim, degree >", "class_non_uniform_dirichlet_b_c_vector.html", null ],
      [ "vectorBCFunction< dim >", "classvector_b_c_function.html", null ]
    ] ],
    [ "GrainSet< dim >", "class_grain_set.html", null ],
    [ "inputFileReader", "classinput_file_reader.html", null ],
    [ "PRISMS::Interpolator< Coordinate, DIM >", "class_p_r_i_s_m_s_1_1_interpolator.html", null ],
    [ "PRISMS::Interpolator< Coordinate, 2 >", "class_p_r_i_s_m_s_1_1_interpolator.html", [
      [ "PRISMS::QuadValues< Coordinate >", "class_p_r_i_s_m_s_1_1_quad_values.html", null ]
    ] ],
    [ "PRISMS::Interpolator< Coordinate, 3 >", "class_p_r_i_s_m_s_1_1_interpolator.html", [
      [ "PRISMS::HexahedronValues< Coordinate >", "class_p_r_i_s_m_s_1_1_hexahedron_values.html", null ]
    ] ],
    [ "materialProperties", "structmaterial_properties.html", null ],
    [ "PRISMS::Mesh< Coordinate, DIM >", "class_p_r_i_s_m_s_1_1_mesh.html", null ],
    [ "modelResidual< dim >", "classmodel_residual.html", null ],
    [ "modelVariable< dim >", "classmodel_variable.html", null ],
    [ "nucleationParameters< dim >", "classnucleation_parameters.html", null ],
    [ "nucleus< dim >", "structnucleus.html", null ],
    [ "OrderParameterRemapper< dim >", "class_order_parameter_remapper.html", null ],
    [ "parallelNucleationList< dim >", "classparallel_nucleation_list.html", null ],
    [ "ParseCommandLineOpts", "class_parse_command_line_opts.html", null ],
    [ "PRISMS::PBasisSet< InType, OutType >", "class_p_r_i_s_m_s_1_1_p_basis_set.html", null ],
    [ "PRISMS::PBasisSetBase< InType, OutType >", "class_p_r_i_s_m_s_1_1_p_basis_set_base.html", null ],
    [ "PRISMS::PFuncBase< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::PFlexFunction< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_flex_function.html", null ],
      [ "PRISMS::PPieceWiseFuncBase< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_piece_wise_func_base.html", null ],
      [ "PRISMS::PSeriesFunction< InType, OutType, VarContainer, IndexContainer >", "class_p_r_i_s_m_s_1_1_p_series_function.html", null ],
      [ "PRISMS::Piece< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_piece.html", null ]
    ] ],
    [ "PRISMS::PFuncBase< Coordinate, FieldType >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::PField< Coordinate, FieldType, DIM >", "class_p_r_i_s_m_s_1_1_p_field.html", null ]
    ] ],
    [ "PRISMS::PFuncBase< double *, double >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::PField< double *, double, dim >", "class_p_r_i_s_m_s_1_1_p_field.html", null ]
    ] ],
    [ "PRISMS::PFuncBase< std::vector< PRISMS::Coordinate< 2 > >, double >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::Quad", "class_p_r_i_s_m_s_1_1_quad.html", null ]
    ] ],
    [ "PRISMS::PFuncBase< std::vector< PRISMS::Coordinate< 3 > >, double >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::Hexahedron", "class_p_r_i_s_m_s_1_1_hexahedron.html", null ]
    ] ],
    [ "PRISMS::PFuncBase< VarContainer, double >", "class_p_r_i_s_m_s_1_1_p_func_base.html", [
      [ "PRISMS::Cu_hardening< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening.html", null ],
      [ "PRISMS::linear_hardening< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening.html", null ],
      [ "PRISMS::neohook< VarContainer >", "class_p_r_i_s_m_s_1_1neohook.html", null ],
      [ "PRISMS::quadlog< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog.html", null ],
      [ "PRISMS::stvenkir< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir.html", null ],
      [ "PRISMS::von_mises< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises.html", null ]
    ] ],
    [ "PRISMS::PFunction< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_function.html", null ],
    [ "PFunctions::pFunction", "class_p_functions_1_1p_function.html", null ],
    [ "PRISMS::PNDArray< OutType >", "class_p_r_i_s_m_s_1_1_p_n_d_array.html", null ],
    [ "PRISMS::PSimpleBase< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_simple_base.html", [
      [ "PRISMS::PPieceWiseSimpleBase< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_piece_wise_simple_base.html", null ],
      [ "PRISMS::SimplePiece< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_simple_piece.html", null ]
    ] ],
    [ "PRISMS::PSimpleBase< std::vector< PRISMS::Coordinate< 2 > >, double >", "class_p_r_i_s_m_s_1_1_p_simple_base.html", [
      [ "PRISMS::Quad_f", "class_p_r_i_s_m_s_1_1_quad__f.html", null ],
      [ "PRISMS::Quad_grad_0", "class_p_r_i_s_m_s_1_1_quad__grad__0.html", null ],
      [ "PRISMS::Quad_grad_1", "class_p_r_i_s_m_s_1_1_quad__grad__1.html", null ],
      [ "PRISMS::Quad_hess_0_0", "class_p_r_i_s_m_s_1_1_quad__hess__0__0.html", null ],
      [ "PRISMS::Quad_hess_0_1", "class_p_r_i_s_m_s_1_1_quad__hess__0__1.html", null ],
      [ "PRISMS::Quad_hess_1_0", "class_p_r_i_s_m_s_1_1_quad__hess__1__0.html", null ],
      [ "PRISMS::Quad_hess_1_1", "class_p_r_i_s_m_s_1_1_quad__hess__1__1.html", null ]
    ] ],
    [ "PRISMS::PSimpleBase< std::vector< PRISMS::Coordinate< 3 > >, double >", "class_p_r_i_s_m_s_1_1_p_simple_base.html", [
      [ "PRISMS::Hexahedron_f", "class_p_r_i_s_m_s_1_1_hexahedron__f.html", null ],
      [ "PRISMS::Hexahedron_grad_0", "class_p_r_i_s_m_s_1_1_hexahedron__grad__0.html", null ],
      [ "PRISMS::Hexahedron_grad_1", "class_p_r_i_s_m_s_1_1_hexahedron__grad__1.html", null ],
      [ "PRISMS::Hexahedron_grad_2", "class_p_r_i_s_m_s_1_1_hexahedron__grad__2.html", null ],
      [ "PRISMS::Hexahedron_hess_0_0", "class_p_r_i_s_m_s_1_1_hexahedron__hess__0__0.html", null ],
      [ "PRISMS::Hexahedron_hess_0_1", "class_p_r_i_s_m_s_1_1_hexahedron__hess__0__1.html", null ],
      [ "PRISMS::Hexahedron_hess_0_2", "class_p_r_i_s_m_s_1_1_hexahedron__hess__0__2.html", null ],
      [ "PRISMS::Hexahedron_hess_1_0", "class_p_r_i_s_m_s_1_1_hexahedron__hess__1__0.html", null ],
      [ "PRISMS::Hexahedron_hess_1_1", "class_p_r_i_s_m_s_1_1_hexahedron__hess__1__1.html", null ],
      [ "PRISMS::Hexahedron_hess_1_2", "class_p_r_i_s_m_s_1_1_hexahedron__hess__1__2.html", null ],
      [ "PRISMS::Hexahedron_hess_2_0", "class_p_r_i_s_m_s_1_1_hexahedron__hess__2__0.html", null ],
      [ "PRISMS::Hexahedron_hess_2_1", "class_p_r_i_s_m_s_1_1_hexahedron__hess__2__1.html", null ],
      [ "PRISMS::Hexahedron_hess_2_2", "class_p_r_i_s_m_s_1_1_hexahedron__hess__2__2.html", null ]
    ] ],
    [ "PRISMS::PSimpleBase< VarContainer, double >", "class_p_r_i_s_m_s_1_1_p_simple_base.html", [
      [ "PRISMS::Cu_hardening_f< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__f.html", null ],
      [ "PRISMS::Cu_hardening_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__grad__0.html", null ],
      [ "PRISMS::Cu_hardening_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__grad__1.html", null ],
      [ "PRISMS::Cu_hardening_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__hess__0__0.html", null ],
      [ "PRISMS::Cu_hardening_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__hess__0__1.html", null ],
      [ "PRISMS::Cu_hardening_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__hess__1__0.html", null ],
      [ "PRISMS::Cu_hardening_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1_cu__hardening__hess__1__1.html", null ],
      [ "PRISMS::linear_hardening_f< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__f.html", null ],
      [ "PRISMS::linear_hardening_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__grad__0.html", null ],
      [ "PRISMS::linear_hardening_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__grad__1.html", null ],
      [ "PRISMS::linear_hardening_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__hess__0__0.html", null ],
      [ "PRISMS::linear_hardening_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__hess__0__1.html", null ],
      [ "PRISMS::linear_hardening_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__hess__1__0.html", null ],
      [ "PRISMS::linear_hardening_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1linear__hardening__hess__1__1.html", null ],
      [ "PRISMS::neohook_f< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__f.html", null ],
      [ "PRISMS::neohook_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__0.html", null ],
      [ "PRISMS::neohook_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__1.html", null ],
      [ "PRISMS::neohook_grad_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__2.html", null ],
      [ "PRISMS::neohook_grad_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__3.html", null ],
      [ "PRISMS::neohook_grad_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__4.html", null ],
      [ "PRISMS::neohook_grad_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__5.html", null ],
      [ "PRISMS::neohook_grad_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__grad__6.html", null ],
      [ "PRISMS::neohook_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__0.html", null ],
      [ "PRISMS::neohook_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__1.html", null ],
      [ "PRISMS::neohook_hess_0_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__2.html", null ],
      [ "PRISMS::neohook_hess_0_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__3.html", null ],
      [ "PRISMS::neohook_hess_0_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__4.html", null ],
      [ "PRISMS::neohook_hess_0_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__5.html", null ],
      [ "PRISMS::neohook_hess_0_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__0__6.html", null ],
      [ "PRISMS::neohook_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__0.html", null ],
      [ "PRISMS::neohook_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__1.html", null ],
      [ "PRISMS::neohook_hess_1_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__2.html", null ],
      [ "PRISMS::neohook_hess_1_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__3.html", null ],
      [ "PRISMS::neohook_hess_1_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__4.html", null ],
      [ "PRISMS::neohook_hess_1_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__5.html", null ],
      [ "PRISMS::neohook_hess_1_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__1__6.html", null ],
      [ "PRISMS::neohook_hess_2_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__0.html", null ],
      [ "PRISMS::neohook_hess_2_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__1.html", null ],
      [ "PRISMS::neohook_hess_2_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__2.html", null ],
      [ "PRISMS::neohook_hess_2_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__3.html", null ],
      [ "PRISMS::neohook_hess_2_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__4.html", null ],
      [ "PRISMS::neohook_hess_2_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__5.html", null ],
      [ "PRISMS::neohook_hess_2_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__2__6.html", null ],
      [ "PRISMS::neohook_hess_3_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__0.html", null ],
      [ "PRISMS::neohook_hess_3_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__1.html", null ],
      [ "PRISMS::neohook_hess_3_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__2.html", null ],
      [ "PRISMS::neohook_hess_3_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__3.html", null ],
      [ "PRISMS::neohook_hess_3_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__4.html", null ],
      [ "PRISMS::neohook_hess_3_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__5.html", null ],
      [ "PRISMS::neohook_hess_3_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__3__6.html", null ],
      [ "PRISMS::neohook_hess_4_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__0.html", null ],
      [ "PRISMS::neohook_hess_4_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__1.html", null ],
      [ "PRISMS::neohook_hess_4_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__2.html", null ],
      [ "PRISMS::neohook_hess_4_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__3.html", null ],
      [ "PRISMS::neohook_hess_4_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__4.html", null ],
      [ "PRISMS::neohook_hess_4_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__5.html", null ],
      [ "PRISMS::neohook_hess_4_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__4__6.html", null ],
      [ "PRISMS::neohook_hess_5_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__0.html", null ],
      [ "PRISMS::neohook_hess_5_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__1.html", null ],
      [ "PRISMS::neohook_hess_5_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__2.html", null ],
      [ "PRISMS::neohook_hess_5_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__3.html", null ],
      [ "PRISMS::neohook_hess_5_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__4.html", null ],
      [ "PRISMS::neohook_hess_5_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__5.html", null ],
      [ "PRISMS::neohook_hess_5_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__5__6.html", null ],
      [ "PRISMS::neohook_hess_6_0< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__0.html", null ],
      [ "PRISMS::neohook_hess_6_1< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__1.html", null ],
      [ "PRISMS::neohook_hess_6_2< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__2.html", null ],
      [ "PRISMS::neohook_hess_6_3< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__3.html", null ],
      [ "PRISMS::neohook_hess_6_4< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__4.html", null ],
      [ "PRISMS::neohook_hess_6_5< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__5.html", null ],
      [ "PRISMS::neohook_hess_6_6< VarContainer >", "class_p_r_i_s_m_s_1_1neohook__hess__6__6.html", null ],
      [ "PRISMS::quadlog_f< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__f.html", null ],
      [ "PRISMS::quadlog_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__0.html", null ],
      [ "PRISMS::quadlog_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__1.html", null ],
      [ "PRISMS::quadlog_grad_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__2.html", null ],
      [ "PRISMS::quadlog_grad_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__3.html", null ],
      [ "PRISMS::quadlog_grad_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__4.html", null ],
      [ "PRISMS::quadlog_grad_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__5.html", null ],
      [ "PRISMS::quadlog_grad_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__grad__6.html", null ],
      [ "PRISMS::quadlog_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__0.html", null ],
      [ "PRISMS::quadlog_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__1.html", null ],
      [ "PRISMS::quadlog_hess_0_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__2.html", null ],
      [ "PRISMS::quadlog_hess_0_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__3.html", null ],
      [ "PRISMS::quadlog_hess_0_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__4.html", null ],
      [ "PRISMS::quadlog_hess_0_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__5.html", null ],
      [ "PRISMS::quadlog_hess_0_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__0__6.html", null ],
      [ "PRISMS::quadlog_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__0.html", null ],
      [ "PRISMS::quadlog_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__1.html", null ],
      [ "PRISMS::quadlog_hess_1_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__2.html", null ],
      [ "PRISMS::quadlog_hess_1_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__3.html", null ],
      [ "PRISMS::quadlog_hess_1_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__4.html", null ],
      [ "PRISMS::quadlog_hess_1_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__5.html", null ],
      [ "PRISMS::quadlog_hess_1_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__1__6.html", null ],
      [ "PRISMS::quadlog_hess_2_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__0.html", null ],
      [ "PRISMS::quadlog_hess_2_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__1.html", null ],
      [ "PRISMS::quadlog_hess_2_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__2.html", null ],
      [ "PRISMS::quadlog_hess_2_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__3.html", null ],
      [ "PRISMS::quadlog_hess_2_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__4.html", null ],
      [ "PRISMS::quadlog_hess_2_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__5.html", null ],
      [ "PRISMS::quadlog_hess_2_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__2__6.html", null ],
      [ "PRISMS::quadlog_hess_3_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__0.html", null ],
      [ "PRISMS::quadlog_hess_3_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__1.html", null ],
      [ "PRISMS::quadlog_hess_3_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__2.html", null ],
      [ "PRISMS::quadlog_hess_3_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__3.html", null ],
      [ "PRISMS::quadlog_hess_3_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__4.html", null ],
      [ "PRISMS::quadlog_hess_3_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__5.html", null ],
      [ "PRISMS::quadlog_hess_3_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__3__6.html", null ],
      [ "PRISMS::quadlog_hess_4_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__0.html", null ],
      [ "PRISMS::quadlog_hess_4_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__1.html", null ],
      [ "PRISMS::quadlog_hess_4_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__2.html", null ],
      [ "PRISMS::quadlog_hess_4_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__3.html", null ],
      [ "PRISMS::quadlog_hess_4_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__4.html", null ],
      [ "PRISMS::quadlog_hess_4_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__5.html", null ],
      [ "PRISMS::quadlog_hess_4_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__4__6.html", null ],
      [ "PRISMS::quadlog_hess_5_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__0.html", null ],
      [ "PRISMS::quadlog_hess_5_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__1.html", null ],
      [ "PRISMS::quadlog_hess_5_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__2.html", null ],
      [ "PRISMS::quadlog_hess_5_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__3.html", null ],
      [ "PRISMS::quadlog_hess_5_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__4.html", null ],
      [ "PRISMS::quadlog_hess_5_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__5.html", null ],
      [ "PRISMS::quadlog_hess_5_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__5__6.html", null ],
      [ "PRISMS::quadlog_hess_6_0< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__0.html", null ],
      [ "PRISMS::quadlog_hess_6_1< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__1.html", null ],
      [ "PRISMS::quadlog_hess_6_2< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__2.html", null ],
      [ "PRISMS::quadlog_hess_6_3< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__3.html", null ],
      [ "PRISMS::quadlog_hess_6_4< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__4.html", null ],
      [ "PRISMS::quadlog_hess_6_5< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__5.html", null ],
      [ "PRISMS::quadlog_hess_6_6< VarContainer >", "class_p_r_i_s_m_s_1_1quadlog__hess__6__6.html", null ],
      [ "PRISMS::stvenkir_f< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__f.html", null ],
      [ "PRISMS::stvenkir_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__0.html", null ],
      [ "PRISMS::stvenkir_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__1.html", null ],
      [ "PRISMS::stvenkir_grad_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__2.html", null ],
      [ "PRISMS::stvenkir_grad_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__3.html", null ],
      [ "PRISMS::stvenkir_grad_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__4.html", null ],
      [ "PRISMS::stvenkir_grad_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__5.html", null ],
      [ "PRISMS::stvenkir_grad_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__grad__6.html", null ],
      [ "PRISMS::stvenkir_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__0.html", null ],
      [ "PRISMS::stvenkir_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__1.html", null ],
      [ "PRISMS::stvenkir_hess_0_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__2.html", null ],
      [ "PRISMS::stvenkir_hess_0_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__3.html", null ],
      [ "PRISMS::stvenkir_hess_0_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__4.html", null ],
      [ "PRISMS::stvenkir_hess_0_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__5.html", null ],
      [ "PRISMS::stvenkir_hess_0_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__0__6.html", null ],
      [ "PRISMS::stvenkir_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__0.html", null ],
      [ "PRISMS::stvenkir_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__1.html", null ],
      [ "PRISMS::stvenkir_hess_1_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__2.html", null ],
      [ "PRISMS::stvenkir_hess_1_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__3.html", null ],
      [ "PRISMS::stvenkir_hess_1_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__4.html", null ],
      [ "PRISMS::stvenkir_hess_1_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__5.html", null ],
      [ "PRISMS::stvenkir_hess_1_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__1__6.html", null ],
      [ "PRISMS::stvenkir_hess_2_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__0.html", null ],
      [ "PRISMS::stvenkir_hess_2_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__1.html", null ],
      [ "PRISMS::stvenkir_hess_2_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__2.html", null ],
      [ "PRISMS::stvenkir_hess_2_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__3.html", null ],
      [ "PRISMS::stvenkir_hess_2_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__4.html", null ],
      [ "PRISMS::stvenkir_hess_2_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__5.html", null ],
      [ "PRISMS::stvenkir_hess_2_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__2__6.html", null ],
      [ "PRISMS::stvenkir_hess_3_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__0.html", null ],
      [ "PRISMS::stvenkir_hess_3_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__1.html", null ],
      [ "PRISMS::stvenkir_hess_3_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__2.html", null ],
      [ "PRISMS::stvenkir_hess_3_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__3.html", null ],
      [ "PRISMS::stvenkir_hess_3_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__4.html", null ],
      [ "PRISMS::stvenkir_hess_3_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__5.html", null ],
      [ "PRISMS::stvenkir_hess_3_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__3__6.html", null ],
      [ "PRISMS::stvenkir_hess_4_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__0.html", null ],
      [ "PRISMS::stvenkir_hess_4_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__1.html", null ],
      [ "PRISMS::stvenkir_hess_4_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__2.html", null ],
      [ "PRISMS::stvenkir_hess_4_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__3.html", null ],
      [ "PRISMS::stvenkir_hess_4_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__4.html", null ],
      [ "PRISMS::stvenkir_hess_4_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__5.html", null ],
      [ "PRISMS::stvenkir_hess_4_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__4__6.html", null ],
      [ "PRISMS::stvenkir_hess_5_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__0.html", null ],
      [ "PRISMS::stvenkir_hess_5_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__1.html", null ],
      [ "PRISMS::stvenkir_hess_5_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__2.html", null ],
      [ "PRISMS::stvenkir_hess_5_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__3.html", null ],
      [ "PRISMS::stvenkir_hess_5_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__4.html", null ],
      [ "PRISMS::stvenkir_hess_5_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__5.html", null ],
      [ "PRISMS::stvenkir_hess_5_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__5__6.html", null ],
      [ "PRISMS::stvenkir_hess_6_0< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__0.html", null ],
      [ "PRISMS::stvenkir_hess_6_1< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__1.html", null ],
      [ "PRISMS::stvenkir_hess_6_2< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__2.html", null ],
      [ "PRISMS::stvenkir_hess_6_3< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__3.html", null ],
      [ "PRISMS::stvenkir_hess_6_4< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__4.html", null ],
      [ "PRISMS::stvenkir_hess_6_5< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__5.html", null ],
      [ "PRISMS::stvenkir_hess_6_6< VarContainer >", "class_p_r_i_s_m_s_1_1stvenkir__hess__6__6.html", null ],
      [ "PRISMS::von_mises_f< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__f.html", null ],
      [ "PRISMS::von_mises_grad_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__0.html", null ],
      [ "PRISMS::von_mises_grad_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__1.html", null ],
      [ "PRISMS::von_mises_grad_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__2.html", null ],
      [ "PRISMS::von_mises_grad_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__3.html", null ],
      [ "PRISMS::von_mises_grad_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__4.html", null ],
      [ "PRISMS::von_mises_grad_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__5.html", null ],
      [ "PRISMS::von_mises_grad_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__6.html", null ],
      [ "PRISMS::von_mises_grad_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__grad__7.html", null ],
      [ "PRISMS::von_mises_hess_0_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__0.html", null ],
      [ "PRISMS::von_mises_hess_0_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__1.html", null ],
      [ "PRISMS::von_mises_hess_0_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__2.html", null ],
      [ "PRISMS::von_mises_hess_0_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__3.html", null ],
      [ "PRISMS::von_mises_hess_0_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__4.html", null ],
      [ "PRISMS::von_mises_hess_0_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__5.html", null ],
      [ "PRISMS::von_mises_hess_0_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__6.html", null ],
      [ "PRISMS::von_mises_hess_0_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__0__7.html", null ],
      [ "PRISMS::von_mises_hess_1_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__0.html", null ],
      [ "PRISMS::von_mises_hess_1_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__1.html", null ],
      [ "PRISMS::von_mises_hess_1_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__2.html", null ],
      [ "PRISMS::von_mises_hess_1_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__3.html", null ],
      [ "PRISMS::von_mises_hess_1_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__4.html", null ],
      [ "PRISMS::von_mises_hess_1_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__5.html", null ],
      [ "PRISMS::von_mises_hess_1_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__6.html", null ],
      [ "PRISMS::von_mises_hess_1_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__1__7.html", null ],
      [ "PRISMS::von_mises_hess_2_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__0.html", null ],
      [ "PRISMS::von_mises_hess_2_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__1.html", null ],
      [ "PRISMS::von_mises_hess_2_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__2.html", null ],
      [ "PRISMS::von_mises_hess_2_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__3.html", null ],
      [ "PRISMS::von_mises_hess_2_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__4.html", null ],
      [ "PRISMS::von_mises_hess_2_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__5.html", null ],
      [ "PRISMS::von_mises_hess_2_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__6.html", null ],
      [ "PRISMS::von_mises_hess_2_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__2__7.html", null ],
      [ "PRISMS::von_mises_hess_3_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__0.html", null ],
      [ "PRISMS::von_mises_hess_3_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__1.html", null ],
      [ "PRISMS::von_mises_hess_3_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__2.html", null ],
      [ "PRISMS::von_mises_hess_3_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__3.html", null ],
      [ "PRISMS::von_mises_hess_3_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__4.html", null ],
      [ "PRISMS::von_mises_hess_3_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__5.html", null ],
      [ "PRISMS::von_mises_hess_3_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__6.html", null ],
      [ "PRISMS::von_mises_hess_3_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__3__7.html", null ],
      [ "PRISMS::von_mises_hess_4_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__0.html", null ],
      [ "PRISMS::von_mises_hess_4_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__1.html", null ],
      [ "PRISMS::von_mises_hess_4_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__2.html", null ],
      [ "PRISMS::von_mises_hess_4_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__3.html", null ],
      [ "PRISMS::von_mises_hess_4_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__4.html", null ],
      [ "PRISMS::von_mises_hess_4_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__5.html", null ],
      [ "PRISMS::von_mises_hess_4_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__6.html", null ],
      [ "PRISMS::von_mises_hess_4_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__4__7.html", null ],
      [ "PRISMS::von_mises_hess_5_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__0.html", null ],
      [ "PRISMS::von_mises_hess_5_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__1.html", null ],
      [ "PRISMS::von_mises_hess_5_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__2.html", null ],
      [ "PRISMS::von_mises_hess_5_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__3.html", null ],
      [ "PRISMS::von_mises_hess_5_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__4.html", null ],
      [ "PRISMS::von_mises_hess_5_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__5.html", null ],
      [ "PRISMS::von_mises_hess_5_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__6.html", null ],
      [ "PRISMS::von_mises_hess_5_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__5__7.html", null ],
      [ "PRISMS::von_mises_hess_6_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__0.html", null ],
      [ "PRISMS::von_mises_hess_6_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__1.html", null ],
      [ "PRISMS::von_mises_hess_6_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__2.html", null ],
      [ "PRISMS::von_mises_hess_6_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__3.html", null ],
      [ "PRISMS::von_mises_hess_6_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__4.html", null ],
      [ "PRISMS::von_mises_hess_6_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__5.html", null ],
      [ "PRISMS::von_mises_hess_6_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__6.html", null ],
      [ "PRISMS::von_mises_hess_6_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__6__7.html", null ],
      [ "PRISMS::von_mises_hess_7_0< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__0.html", null ],
      [ "PRISMS::von_mises_hess_7_1< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__1.html", null ],
      [ "PRISMS::von_mises_hess_7_2< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__2.html", null ],
      [ "PRISMS::von_mises_hess_7_3< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__3.html", null ],
      [ "PRISMS::von_mises_hess_7_4< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__4.html", null ],
      [ "PRISMS::von_mises_hess_7_5< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__5.html", null ],
      [ "PRISMS::von_mises_hess_7_6< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__6.html", null ],
      [ "PRISMS::von_mises_hess_7_7< VarContainer >", "class_p_r_i_s_m_s_1_1von__mises__hess__7__7.html", null ]
    ] ],
    [ "PRISMS::PSimpleFunction< VarContainer, OutType >", "class_p_r_i_s_m_s_1_1_p_simple_function.html", null ],
    [ "RefinementCriterion", "class_refinement_criterion.html", null ],
    [ "SimplifiedGrainManipulator< dim >", "class_simplified_grain_manipulator.html", null ],
    [ "SimplifiedGrainRepresentation< dim >", "class_simplified_grain_representation.html", null ],
    [ "SolverParametersBase", "class_solver_parameters_base.html", [
      [ "LinearSolverParameters", "class_linear_solver_parameters.html", null ],
      [ "NonlinearSolverParameters", "class_nonlinear_solver_parameters.html", null ]
    ] ],
    [ "staticCondensation< _dof1, _dof2 >", "classstatic_condensation.html", null ],
    [ "Subscriptor", null, [
      [ "MatrixFreePDE< dim, 1 >", "class_matrix_free_p_d_e.html", null ],
      [ "MultiPhysicsBVP< dim, 1 >", "class_multi_physics_b_v_p.html", [
        [ "continuumPlasticity< dim >", "classcontinuum_plasticity.html", null ],
        [ "crystalPlasticity< dim >", "classcrystal_plasticity.html", null ]
      ] ],
      [ "MatrixFreePDE< dim, degree >", "class_matrix_free_p_d_e.html", null ],
      [ "MultiPhysicsBVP< dim, degree >", "class_multi_physics_b_v_p.html", null ]
    ] ],
    [ "userInputParameters_cp", "classuser_input_parameters__cp.html", null ],
    [ "userInputParameters_pf< dim >", "classuser_input_parameters__pf.html", null ],
    [ "varBCs< dim >", "classvar_b_cs.html", null ],
    [ "variable_info", "structvariable__info.html", null ],
    [ "variableAttributeLoader", "classvariable_attribute_loader.html", null ],
    [ "variableContainer< dim, degree, T >", "classvariable_container.html", null ],
    [ "variableValueContainer", "classvariable_value_container.html", null ]
];