#ifndef INCLUDE_MATRIXFREEPDE_TEMPLATE_INSTANTIATIONS_H_
#define INCLUDE_MATRIXFREEPDE_TEMPLATE_INSTANTIATIONS_H_

#ifndef MATRIXFREEPDE_TEMPLATE_INSTANTIATION
#define MATRIXFREEPDE_TEMPLATE_INSTANTIATION
template class MatrixFreePDE<2,1>;
template class MatrixFreePDE<3,1>;
#endif

#endif /* INCLUDE_MATRIXFREEPDE_TEMPLATE_INSTANTIATIONS_H_ */